language: node_js
node_js: "10"

before_install: |
  npm config set @dogamak:registry https://npm.pkg.github.com
  npm config set '//npm.pkg.github.com/:_authToken' "$GPR_TOKEN"

install: npm install

script: npm run build

deploy:
  - edge: true
    provider: script
    script: ./deploy.sh production
    on:
      all_branch: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+$
  - edge: true
    provider: script
    script: ./deploy.sh staging
    on:
      all_branch: true
      condition: $TRAVIS_TAG =~ ^v[0-9]+\.[0-9]+\.[0-9]+-
