name: Webpack

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
    - name: npm install, build, and test
      run: |
        npm config set @dogamak:registry https://npm.pkg.github.com
        npm ci
        npm run build
      env:
        CI: true
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
